### ISSUE TITLE
Add gitignore file

### ISSUE THREAD

**Issue by NellyNakhero** [Tech-Sisters-Kenya/todo_sample_app#8]
git ignore should prevent commit of node modules and package-lock.json

**Comment by NellyNakhero** [comment]
i'll be working on this :)

**Comment by cesswairimu** [comment]
Good catch @NellyNakhero :tada: thanks, and thanks for the PR too  :+1:

**Comment by cesswairimu** [comment]
This was fixed in https://github.com/Tech-Sisters-Kenya/todo_sample_app/issues/8
